(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    (display newline)
    (display "cops will comes within 1 minute!")
    (display newline))
  (define (dispatch passwd m)
    (let ((error-number 0))
      (cond ((not (eq? passwd password))
           (if (>= error-number 7) (call-the-cops)
             (begin
               (set! error-number (+ 1 error-number))
               "incorrect password")))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m)))))
  dispatch)
